### ISSUE TITLE
SelectMany+Concat Error

### ISSUE THREAD

**Issue by xuming314** [skgmn/fromjs#2]
var petOwners = [
    { name: "ab", pets: [ "a", "b" ] },
    { name: "cd", pets: [ "c", "d" ] },
    { name: "ef", pets: [ "e", "f" ] } 
];
from(petOwners).selectMany("$pets").concat(["x","y"]).toArray();

result:["a", "b", "c", "d", "e", "f"]
not ["a", "b", "c", "d", "e", "f", "x", "y"]

**Comment by skgmn** [comment]
It was a bug of selectMany(). Fixed. Thank you.
