### ISSUE TITLE
fromjs no "indexOf" function

### ISSUE THREAD

**Issue by xuming314** [skgmn/fromjs#3]
var arr2 = [
  {name: "a", color: "yellow"},
  {name: "b", color: "red"},
  {name: "c", color: "blue"},
  {name: "c", color: "blue"}
];  
var val2 = from(arr2).indexOf("$color==@","red");

//result:val2=1

**Comment by skgmn** [comment]
It was normal that fromjs didn't provide indexOf().
It could be achieved by

```
var val2 = from(arr2).where('$color==@', 'red').select('$$').first();
```

But the way was hard to be inferred, so I added indexOf() which acts as a shortcut of that.
