### ISSUE TITLE
Set function context

### ISSUE THREAD

**Issue by calebboyd** [skgmn/fromjs#6]
A nice feature, though It might affect performance (minimal), would be the ability to set function execution context (this). In other words in `***Iterable.prototype.each` functions using `f.call(context,arg1,arg2,arg3,)` instead of `f(arg1,arg2,arg3)` and similarly with non-eval'd `proc` lambdas. I can submit a pull request if this is something you might consider!

**Comment by skgmn** [comment]
It's a good idea but there's no proper interface currently to retrieve 'context' parameter. I'll try to find an appropriate way to do it. Any ideas are welcome. Thank you.
