### ISSUE TITLE
singleOrDefault

### ISSUE THREAD

**Issue by furier** [skgmn/fromjs#7]
The sequence has more than one element satisfying the condition. I am very sure that my list of strings, which I inspect with break points in webstorm does not contain multiple objects which satisfy the condition.

```
var type = 'subst';
var filePaths = ['./lib/hangman/wordlists/adv.nor.wordlist.txt',
                 './lib/hangman/wordlists/subst.nor.wordlist.txt']

var path = from(filePaths).singleOrDefault(function(x){ return S(x).contains('/' + type + '.'); });
```

the error thrown  is "The sequence has more than one element satisfying the condition";

```
var path = from(filePaths).singleOrDefault(function(x){ return x.indexOf(type) !== -1; });
```

this live gives the same result.

**Comment by skgmn** [comment]
When singleOrDefault() is called with only one parameter, the parameter is considered as a 'defaultValue', not a predicator. That's why the function call you've written didn't operate as you think. You'd better use single(), rather than singleOrDefault().

**Comment by furier** [comment]
okay, I can see that, but anyways this results in its not possible to use lambda with this function? like this

```
singleOrDefault('$.indexOf(@) !== -1', type)
```

**Comment by skgmn** [comment]
It has to be like below to achieve your goal.

```
singleOrDefault('$.indexOf(@) !== -1', null, type)
```

You have to insert any default value into 2nd parameter (null in this case), and then place an external argument on the 3rd position.

But it won't work well for now, actually it is a bug :(
I just found it by virtue of your report. Thank you.
Gonna update.

**Comment by furier** [comment]
thank you! yeah I tried the version you gave me also, and had no luck with it either. good we got to make it all better! :)

**Comment by skgmn** [comment]
Updated. :)
